global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fantasy-cricket-api'
    static_configs:
      - targets: ['fantasy_cricket_api:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'postgresql'
    static_configs:
      - targets: ['fantasy_cricket_db:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['fantasy_cricket_redis:9121']

  - job_name: 'nginx'
    static_configs:
      - targets: ['fantasy_cricket_nginx:9113']